[package]
name = "subsystem-for-arxumbra"
version = "0.0.0-s0"
edition = "2024"

[dependencies]
bevy = { version = "=0.20.0-rc.2", default-features = false, features = [
    "std",
    "multi_threaded",
    "async_executor",
    "bevy_asset",
    "bevy_log",
    "bevy_state",
    "reflect_auto_register",
    "bevy_winit",
    "wayland",
    "bevy_window",
    "bevy_render",
    "bevy_core_pipeline",
    "bevy_post_process",
    "bevy_mesh",
    "bevy_camera",
    "bevy_image",
    "bevy_sprite",
    "bevy_sprite_render",
    "ktx2",
    "basis-universal",
    "zstd_rust",
] }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"
